-- PayFlow production-ready Supabase schema
-- Run this file once in Supabase Dashboard > SQL Editor.
-- It preserves the existing users / kyc_requests / exchange_rates tables and extends them.

begin;

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- 1. Core tables and safe extensions to the current schema
-- ---------------------------------------------------------------------------

create table if not exists public.users (
  user_id bigint generated by default as identity primary key,
  full_name varchar,
  email varchar unique,
  phone_number varchar unique,
  balance_yer numeric(20,2) default 0,
  balance_usdt numeric(20,8) default 0,
  kyc_status varchar default 'NOT_SUBMITTED',
  is_active int2 default 1,
  created_at timestamptz default now(),
  password_hash text,
  role text default 'USER',
  balance numeric(20,8) default 0
);

alter table public.users add column if not exists auth_user_id uuid;
alter table public.users add column if not exists deleted_at timestamptz;
alter table public.users add column if not exists deleted_reason text;
alter table public.users add column if not exists updated_at timestamptz default now();
alter table public.users alter column balance_usdt set default 0;
alter table public.users alter column balance_yer set default 0;
alter table public.users alter column balance set default 0;
alter table public.users alter column role set default 'USER';
alter table public.users alter column kyc_status set default 'NOT_SUBMITTED';
alter table public.users alter column is_active set default 1;
alter table public.users alter column created_at set default now();

update public.users
set balance_usdt = coalesce(balance_usdt, balance, 0),
    balance_yer = coalesce(balance_yer, 0),
    balance = coalesce(balance_usdt, balance, 0),
    role = upper(coalesce(role, 'USER')),
    kyc_status = upper(coalesce(kyc_status, 'NOT_SUBMITTED')),
    is_active = coalesce(is_active, 1),
    created_at = coalesce(created_at, now());

create unique index if not exists users_auth_user_id_key on public.users(auth_user_id) where auth_user_id is not null;
create unique index if not exists users_email_lower_key on public.users(lower(email)) where email is not null;
create unique index if not exists users_phone_number_key on public.users(phone_number) where phone_number is not null;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'users_auth_user_id_fkey') then
    alter table public.users add constraint users_auth_user_id_fkey foreign key (auth_user_id) references auth.users(id) on delete set null;
  end if;
end $$;

create table if not exists public.kyc_requests (
  kyc_id bigint generated by default as identity primary key,
  user_id bigint not null,
  document_type varchar not null,
  document_number varchar not null,
  status varchar default 'PENDING',
  rejection_reason varchar,
  reviewed_by varchar,
  created_at timestamptz default now(),
  updated_at timestamptz
);

alter table public.kyc_requests add column if not exists document_front_path text;
alter table public.kyc_requests add column if not exists document_back_path text;
alter table public.kyc_requests add column if not exists selfie_path text;
alter table public.kyc_requests add column if not exists reviewed_at timestamptz;
alter table public.kyc_requests alter column status set default 'PENDING';
alter table public.kyc_requests alter column created_at set default now();

create table if not exists public.exchange_rates (
  rate_id bigint generated by default as identity primary key,
  buy_rate numeric(20,4) not null default 535,
  sell_rate numeric(20,4) not null default 545,
  fee_percentage numeric(8,4) not null default 0,
  withdrawal_fee_usdt numeric(20,8) not null default 1,
  updated_at timestamptz default now(),
  updated_by bigint
);

alter table public.exchange_rates add column if not exists buy_rate numeric(20,4) default 535;
alter table public.exchange_rates add column if not exists sell_rate numeric(20,4) default 545;
alter table public.exchange_rates add column if not exists fee_percentage numeric(8,4) default 0;
alter table public.exchange_rates add column if not exists withdrawal_fee_usdt numeric(20,8) default 1;
alter table public.exchange_rates add column if not exists updated_at timestamptz default now();
alter table public.exchange_rates add column if not exists updated_by bigint;

insert into public.exchange_rates (buy_rate, sell_rate, fee_percentage, withdrawal_fee_usdt)
select 535, 545, 0, 1
where not exists (select 1 from public.exchange_rates);

create table if not exists public.payment_methods (
  method_id bigint generated by default as identity primary key,
  name varchar(120) not null,
  category varchar(20) not null default 'BOTH' check (category in ('DEPOSIT','WITHDRAW','BOTH')),
  account_name varchar(160),
  account_number varchar(160),
  instructions text,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists payment_methods_name_key on public.payment_methods(lower(name));

create table if not exists public.deposit_requests (
  deposit_id bigint generated by default as identity primary key,
  reference text unique,
  user_id bigint not null,
  payment_method_id bigint,
  payment_method varchar(160),
  deposit_method varchar(160),
  amount_yer numeric(20,2) not null default 0,
  gross_usdt numeric(20,8) not null default 0,
  fee_usdt numeric(20,8) not null default 0,
  net_usdt numeric(20,8) not null default 0,
  proof_path text,
  proof_ref text,
  proof_image text,
  sender_name varchar(160),
  sender_phone varchar(40),
  status varchar(20) not null default 'PENDING',
  admin_note text,
  reviewed_by bigint,
  created_at timestamptz not null default now(),
  processed_at timestamptz
);

alter table public.deposit_requests add column if not exists reference text;
alter table public.deposit_requests add column if not exists payment_method_id bigint;
alter table public.deposit_requests add column if not exists payment_method varchar(160);
alter table public.deposit_requests add column if not exists deposit_method varchar(160);
alter table public.deposit_requests add column if not exists amount_yer numeric(20,2) default 0;
alter table public.deposit_requests add column if not exists gross_usdt numeric(20,8) default 0;
alter table public.deposit_requests add column if not exists fee_usdt numeric(20,8) default 0;
alter table public.deposit_requests add column if not exists net_usdt numeric(20,8) default 0;
alter table public.deposit_requests add column if not exists proof_path text;
alter table public.deposit_requests add column if not exists proof_ref text;
alter table public.deposit_requests add column if not exists proof_image text;
alter table public.deposit_requests add column if not exists sender_name varchar(160);
alter table public.deposit_requests add column if not exists sender_phone varchar(40);
alter table public.deposit_requests add column if not exists status varchar(20) default 'PENDING';
alter table public.deposit_requests add column if not exists admin_note text;
alter table public.deposit_requests add column if not exists reviewed_by bigint;
alter table public.deposit_requests add column if not exists created_at timestamptz default now();
alter table public.deposit_requests add column if not exists processed_at timestamptz;
create unique index if not exists deposit_requests_reference_key on public.deposit_requests(reference) where reference is not null;

create table if not exists public.withdraw_requests (
  withdraw_id bigint generated by default as identity primary key,
  reference text unique,
  user_id bigint not null,
  payout_type varchar(30) not null,
  amount_usdt numeric(20,8) not null,
  fee_usdt numeric(20,8) not null default 0,
  net_usdt numeric(20,8) not null,
  amount_yer numeric(20,2),
  exchange_rate numeric(20,4),
  network varchar(30),
  destination text not null,
  payment_method_id bigint,
  beneficiary_name varchar(160),
  status varchar(20) not null default 'PENDING',
  admin_note text,
  reviewed_by bigint,
  created_at timestamptz not null default now(),
  processed_at timestamptz
);

alter table public.withdraw_requests add column if not exists reference text;
alter table public.withdraw_requests add column if not exists withdraw_id bigint generated by default as identity;
alter table public.withdraw_requests add column if not exists payout_type varchar(30) default 'EXTERNAL_USDT';
alter table public.withdraw_requests add column if not exists amount_usdt numeric(20,8) default 0;
alter table public.withdraw_requests add column if not exists fee_usdt numeric(20,8) default 0;
alter table public.withdraw_requests add column if not exists net_usdt numeric(20,8) default 0;
alter table public.withdraw_requests add column if not exists amount_yer numeric(20,2);
alter table public.withdraw_requests add column if not exists exchange_rate numeric(20,4);
alter table public.withdraw_requests add column if not exists network varchar(30);
alter table public.withdraw_requests add column if not exists destination text;
alter table public.withdraw_requests add column if not exists payment_method_id bigint;
alter table public.withdraw_requests add column if not exists beneficiary_name varchar(160);
alter table public.withdraw_requests add column if not exists status varchar(20) default 'PENDING';
alter table public.withdraw_requests add column if not exists admin_note text;
alter table public.withdraw_requests add column if not exists reviewed_by bigint;
alter table public.withdraw_requests add column if not exists created_at timestamptz default now();
alter table public.withdraw_requests add column if not exists processed_at timestamptz;
create unique index if not exists withdraw_requests_reference_key on public.withdraw_requests(reference) where reference is not null;
create unique index if not exists withdraw_requests_withdraw_id_key on public.withdraw_requests(withdraw_id);

create table if not exists public.transactions (
  transaction_id bigint generated by default as identity primary key,
  reference text not null,
  user_id bigint not null,
  request_id bigint,
  type varchar(30) not null,
  status varchar(20) not null default 'PENDING',
  currency varchar(10) not null default 'USDT',
  amount_usdt numeric(20,8),
  amount_yer numeric(20,2),
  balance_after numeric(20,8),
  description text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists transactions_user_created_idx on public.transactions(user_id, created_at desc);
create index if not exists transactions_reference_idx on public.transactions(reference);
create index if not exists transactions_status_idx on public.transactions(status, created_at desc);

create table if not exists public.notifications (
  notification_id bigint generated by default as identity primary key,
  user_id bigint,
  audience varchar(10) not null default 'USER' check (audience in ('USER','ADMIN')),
  title varchar(160) not null,
  message text not null,
  icon varchar(80),
  reference text,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists notifications_user_created_idx on public.notifications(user_id, created_at desc);
create index if not exists notifications_admin_created_idx on public.notifications(audience, created_at desc);

create table if not exists public.audit_logs (
  audit_id bigint generated by default as identity primary key,
  actor_user_id bigint,
  action varchar(100) not null,
  entity_type varchar(60) not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Add foreign keys only if they do not already exist.
do $$
begin
  if not exists (select 1 from pg_constraint where conname='kyc_requests_user_id_fkey') then alter table public.kyc_requests add constraint kyc_requests_user_id_fkey foreign key(user_id) references public.users(user_id) not valid; end if;
  if not exists (select 1 from pg_constraint where conname='deposit_requests_user_id_fkey') then alter table public.deposit_requests add constraint deposit_requests_user_id_fkey foreign key(user_id) references public.users(user_id) not valid; end if;
  if not exists (select 1 from pg_constraint where conname='deposit_requests_payment_method_id_fkey') then alter table public.deposit_requests add constraint deposit_requests_payment_method_id_fkey foreign key(payment_method_id) references public.payment_methods(method_id) not valid; end if;
  if not exists (select 1 from pg_constraint where conname='withdraw_requests_user_id_fkey') then alter table public.withdraw_requests add constraint withdraw_requests_user_id_fkey foreign key(user_id) references public.users(user_id) not valid; end if;
  if not exists (select 1 from pg_constraint where conname='withdraw_requests_payment_method_id_fkey') then alter table public.withdraw_requests add constraint withdraw_requests_payment_method_id_fkey foreign key(payment_method_id) references public.payment_methods(method_id) not valid; end if;
  if not exists (select 1 from pg_constraint where conname='transactions_user_id_fkey') then alter table public.transactions add constraint transactions_user_id_fkey foreign key(user_id) references public.users(user_id) not valid; end if;
  if not exists (select 1 from pg_constraint where conname='notifications_user_id_fkey') then alter table public.notifications add constraint notifications_user_id_fkey foreign key(user_id) references public.users(user_id) not valid; end if;
end $$;

-- ---------------------------------------------------------------------------
-- 2. Shared helpers, profile creation and authorization
-- ---------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at before update on public.users for each row execute function public.set_updated_at();
drop trigger if exists payment_methods_set_updated_at on public.payment_methods;
create trigger payment_methods_set_updated_at before update on public.payment_methods for each row execute function public.set_updated_at();
drop trigger if exists transactions_set_updated_at on public.transactions;
create trigger transactions_set_updated_at before update on public.transactions for each row execute function public.set_updated_at();

create or replace function public.current_profile_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select user_id from public.users
  where auth_user_id = auth.uid() and is_active = 1 and deleted_at is null
  limit 1
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.users
    where auth_user_id = auth.uid()
      and upper(role) = 'ADMIN'
      and is_active = 1
      and deleted_at is null
  )
$$;

create or replace function public.make_reference(prefix text)
returns text
language sql
volatile
set search_path = public
as $$
  select upper(prefix) || '-' || to_char(clock_timestamp(), 'YYMMDD') || '-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8))
$$;

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (auth_user_id, full_name, email, phone_number, role, kyc_status, is_active, balance_usdt, balance_yer, balance, password_hash)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data->>'full_name',''), split_part(new.email,'@',1)),
    lower(new.email),
    nullif(new.raw_user_meta_data->>'phone_number',''),
    'USER', 'NOT_SUBMITTED', 1, 0, 0, 0, null
  )
  on conflict (email) do update
    set auth_user_id = excluded.auth_user_id,
        full_name = coalesce(nullif(public.users.full_name,''), excluded.full_name),
        phone_number = coalesce(public.users.phone_number, excluded.phone_number),
        password_hash = null,
        updated_at = now();
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_auth_user();

-- Link any existing Supabase Auth accounts to existing public profiles.
insert into public.users (auth_user_id, full_name, email, role, kyc_status, is_active, balance_usdt, balance_yer, balance, password_hash)
select au.id,
       coalesce(nullif(au.raw_user_meta_data->>'full_name',''), split_part(au.email,'@',1)),
       lower(au.email), 'USER', 'NOT_SUBMITTED', 1, 0, 0, 0, null
from auth.users au
where au.email is not null
on conflict (email) do update
  set auth_user_id = excluded.auth_user_id,
      password_hash = null,
      updated_at = now();

-- ---------------------------------------------------------------------------
-- 3. User-facing atomic workflows
-- ---------------------------------------------------------------------------

create or replace function public.create_deposit_request(
  p_amount_yer numeric,
  p_payment_method_id bigint,
  p_proof_path text,
  p_sender_name text,
  p_sender_phone text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id bigint := public.current_profile_id();
  v_rate public.exchange_rates%rowtype;
  v_method public.payment_methods%rowtype;
  v_reference text := public.make_reference('DEP');
  v_gross numeric(20,8);
  v_fee numeric(20,8);
  v_net numeric(20,8);
  v_id bigint;
begin
  if v_user_id is null then raise exception 'account_inactive'; end if;
  if p_amount_yer is null or p_amount_yer < 1000 then raise exception 'minimum_deposit_1000_yer'; end if;
  if nullif(trim(p_proof_path),'') is null then raise exception 'proof_required'; end if;

  select * into v_rate from public.exchange_rates order by rate_id limit 1;
  if v_rate.sell_rate is null or v_rate.sell_rate <= 0 then raise exception 'rate_unavailable'; end if;
  select * into v_method from public.payment_methods where method_id=p_payment_method_id and is_active=true and category in ('DEPOSIT','BOTH');
  if not found then raise exception 'payment_method_unavailable'; end if;

  v_gross := round(p_amount_yer / v_rate.sell_rate, 8);
  v_fee := round(v_gross * coalesce(v_rate.fee_percentage,0) / 100, 8);
  v_net := v_gross - v_fee;

  insert into public.deposit_requests(reference,user_id,payment_method_id,payment_method,deposit_method,amount_yer,gross_usdt,fee_usdt,net_usdt,proof_path,proof_ref,sender_name,sender_phone,status)
  values(v_reference,v_user_id,v_method.method_id,v_method.name,v_method.name,p_amount_yer,v_gross,v_fee,v_net,p_proof_path,p_proof_path,p_sender_name,p_sender_phone,'PENDING')
  returning deposit_id into v_id;

  insert into public.transactions(reference,user_id,request_id,type,status,currency,amount_usdt,amount_yer,description,metadata)
  values(v_reference,v_user_id,v_id,'DEPOSIT','PENDING','USDT',v_net,p_amount_yer,'شراء USDT عبر '||v_method.name,jsonb_build_object('rate',v_rate.sell_rate,'fee_usdt',v_fee));

  insert into public.notifications(user_id,audience,title,message,icon,reference)
  values(v_user_id,'USER','تم استلام طلب الإيداع','طلبك '||v_reference||' بانتظار مراجعة الإدارة.','fa-arrow-down',v_reference);
  insert into public.notifications(user_id,audience,title,message,icon,reference)
  values(null,'ADMIN','طلب إيداع جديد','طلب '||v_reference||' بقيمة '||round(v_net,2)||' USDT يحتاج المراجعة.','fa-file-circle-plus',v_reference);

  return jsonb_build_object('deposit_id',v_id,'reference',v_reference,'net_usdt',v_net,'status','PENDING');
end $$;

create or replace function public.create_withdraw_request(
  p_amount_usdt numeric,
  p_payout_type text,
  p_destination text,
  p_network text default null,
  p_payment_method_id bigint default null,
  p_beneficiary_name text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user public.users%rowtype;
  v_rate public.exchange_rates%rowtype;
  v_reference text := public.make_reference('WDR');
  v_fee numeric(20,8);
  v_net numeric(20,8);
  v_yer numeric(20,2);
  v_id bigint;
  v_type text := upper(p_payout_type);
begin
  select * into v_user from public.users where user_id=public.current_profile_id() for update;
  if not found then raise exception 'account_inactive'; end if;
  if upper(coalesce(v_user.kyc_status,'')) <> 'APPROVED' then raise exception 'kyc_required'; end if;
  if p_amount_usdt is null or p_amount_usdt <= 0 then raise exception 'invalid_amount'; end if;
  if coalesce(v_user.balance_usdt,0) < p_amount_usdt then raise exception 'insufficient_balance'; end if;
  if v_type not in ('EXTERNAL_USDT','YER_PAYOUT') then raise exception 'invalid_payout_type'; end if;
  if nullif(trim(p_destination),'') is null then raise exception 'destination_required'; end if;

  select * into v_rate from public.exchange_rates order by rate_id limit 1;
  if v_type = 'EXTERNAL_USDT' then
    if nullif(trim(p_network),'') is null then raise exception 'network_required'; end if;
    v_fee := coalesce(v_rate.withdrawal_fee_usdt,0);
  else
    if p_payment_method_id is null or nullif(trim(p_beneficiary_name),'') is null then raise exception 'payout_details_required'; end if;
    if not exists(select 1 from public.payment_methods where method_id=p_payment_method_id and is_active=true and category in ('WITHDRAW','BOTH')) then raise exception 'payment_method_unavailable'; end if;
    v_fee := round(p_amount_usdt * coalesce(v_rate.fee_percentage,0) / 100,8);
  end if;
  if p_amount_usdt <= v_fee then raise exception 'amount_below_fee'; end if;
  v_net := p_amount_usdt - v_fee;
  if v_type='YER_PAYOUT' then v_yer := round(v_net * v_rate.buy_rate,2); end if;

  update public.users set balance_usdt=balance_usdt-p_amount_usdt,balance=balance_usdt-p_amount_usdt where user_id=v_user.user_id;

  insert into public.withdraw_requests(reference,user_id,payout_type,amount_usdt,fee_usdt,net_usdt,amount_yer,exchange_rate,network,destination,payment_method_id,beneficiary_name,status)
  values(v_reference,v_user.user_id,v_type,p_amount_usdt,v_fee,v_net,v_yer,case when v_type='YER_PAYOUT' then v_rate.buy_rate else null end,p_network,p_destination,p_payment_method_id,p_beneficiary_name,'PENDING')
  returning withdraw_id into v_id;

  insert into public.transactions(reference,user_id,request_id,type,status,currency,amount_usdt,amount_yer,balance_after,description,metadata)
  values(v_reference,v_user.user_id,v_id,case when v_type='YER_PAYOUT' then 'YER_PAYOUT' else 'WITHDRAW' end,'PENDING','USDT',p_amount_usdt,v_yer,v_user.balance_usdt-p_amount_usdt,case when v_type='YER_PAYOUT' then 'بيع USDT واستلام ريال يمني' else 'سحب USDT عبر '||p_network end,jsonb_build_object('fee_usdt',v_fee,'destination',p_destination));

  insert into public.notifications(user_id,audience,title,message,icon,reference)
  values(v_user.user_id,'USER','تم إنشاء طلب السحب','تم حجز المبلغ والطلب '||v_reference||' بانتظار المراجعة.','fa-arrow-up',v_reference);
  insert into public.notifications(user_id,audience,title,message,icon,reference)
  values(null,'ADMIN','طلب سحب جديد','طلب '||v_reference||' بقيمة '||round(p_amount_usdt,2)||' USDT يحتاج المراجعة.','fa-money-bill-transfer',v_reference);

  return jsonb_build_object('withdraw_id',v_id,'reference',v_reference,'status','PENDING','reserved_usdt',p_amount_usdt);
end $$;

create or replace function public.lookup_transfer_recipient(p_identifier text)
returns table(user_id bigint, full_name text, masked_identifier text)
language plpgsql
security definer
set search_path = public
as $$
declare v_self bigint := public.current_profile_id();
begin
  if v_self is null then raise exception 'account_inactive'; end if;
  return query
  select u.user_id,
         u.full_name::text,
         case when lower(u.email)=lower(trim(p_identifier))
           then regexp_replace(u.email, '(^.).*(@.*$)', '\1***\2')
           else '***' || right(u.phone_number,4)
         end::text
  from public.users u
  where u.user_id<>v_self and u.is_active=1 and u.deleted_at is null
    and (lower(u.email)=lower(trim(p_identifier)) or u.phone_number=regexp_replace(trim(p_identifier),'\s','','g'))
  limit 1;
end $$;

create or replace function public.internal_transfer(p_identifier text,p_amount_usdt numeric,p_note text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sender_id bigint := public.current_profile_id();
  v_recipient_id bigint;
  v_sender_balance numeric(20,8);
  v_recipient_balance numeric(20,8);
  v_reference text := public.make_reference('TRF');
begin
  if v_sender_id is null then raise exception 'account_inactive'; end if;
  if p_amount_usdt is null or p_amount_usdt<=0 then raise exception 'invalid_amount'; end if;
  select u.user_id into v_recipient_id from public.users u
    where u.is_active=1 and u.deleted_at is null
      and (lower(u.email)=lower(trim(p_identifier)) or u.phone_number=regexp_replace(trim(p_identifier),'\s','','g'))
    limit 1;
  if v_recipient_id is null then raise exception 'recipient_not_found'; end if;
  if v_recipient_id=v_sender_id then raise exception 'cannot_transfer_to_self'; end if;

  perform pg_advisory_xact_lock(least(v_sender_id,v_recipient_id));
  perform pg_advisory_xact_lock(greatest(v_sender_id,v_recipient_id));
  select balance_usdt into v_sender_balance from public.users where user_id=v_sender_id for update;
  select balance_usdt into v_recipient_balance from public.users where user_id=v_recipient_id for update;
  if coalesce(v_sender_balance,0)<p_amount_usdt then raise exception 'insufficient_balance'; end if;

  update public.users set balance_usdt=balance_usdt-p_amount_usdt,balance=balance_usdt-p_amount_usdt where user_id=v_sender_id;
  update public.users set balance_usdt=balance_usdt+p_amount_usdt,balance=balance_usdt+p_amount_usdt where user_id=v_recipient_id;

  insert into public.transactions(reference,user_id,type,status,currency,amount_usdt,balance_after,description,metadata)
  values
    (v_reference,v_sender_id,'TRANSFER_OUT','COMPLETED','USDT',p_amount_usdt,v_sender_balance-p_amount_usdt,coalesce(p_note,'تحويل داخلي صادر'),jsonb_build_object('counterparty_user_id',v_recipient_id)),
    (v_reference,v_recipient_id,'TRANSFER_IN','COMPLETED','USDT',p_amount_usdt,v_recipient_balance+p_amount_usdt,coalesce(p_note,'تحويل داخلي وارد'),jsonb_build_object('counterparty_user_id',v_sender_id));

  insert into public.notifications(user_id,audience,title,message,icon,reference)
  values
    (v_sender_id,'USER','تم إرسال التحويل','اكتمل التحويل '||v_reference||' بقيمة '||round(p_amount_usdt,2)||' USDT.','fa-arrow-left',v_reference),
    (v_recipient_id,'USER','حوالة واردة','استلمت '||round(p_amount_usdt,2)||' USDT بالمرجع '||v_reference||'.','fa-arrow-right',v_reference);

  return jsonb_build_object('reference',v_reference,'status','COMPLETED','amount_usdt',p_amount_usdt);
end $$;

create or replace function public.submit_kyc_request(p_document_type text,p_document_number text,p_front_path text,p_back_path text,p_selfie_path text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare v_user_id bigint := public.current_profile_id(); v_id bigint;
begin
  if v_user_id is null then raise exception 'account_inactive'; end if;
  if exists(select 1 from public.kyc_requests where user_id=v_user_id and status='PENDING') then raise exception 'kyc_request_already_pending'; end if;
  if upper(p_document_type) not in ('NATIONAL_ID','PASSPORT','DRIVER_LICENSE') then raise exception 'invalid_document_type'; end if;
  if length(trim(p_document_number))<5 or nullif(trim(p_front_path),'') is null or nullif(trim(p_selfie_path),'') is null then raise exception 'missing_kyc_fields'; end if;
  if upper(p_document_type)<>'PASSPORT' and nullif(trim(p_back_path),'') is null then raise exception 'back_document_required'; end if;

  insert into public.kyc_requests(user_id,document_type,document_number,status,document_front_path,document_back_path,selfie_path,created_at,updated_at)
  values(v_user_id,upper(p_document_type),trim(p_document_number),'PENDING',p_front_path,p_back_path,p_selfie_path,now(),now()) returning kyc_id into v_id;
  update public.users set kyc_status='PENDING' where user_id=v_user_id;
  insert into public.notifications(user_id,audience,title,message,icon,reference)
  values(v_user_id,'USER','تم استلام مستنداتك','طلب التوثيق قيد المراجعة.','fa-id-card','KYC-'||v_id),
        (null,'ADMIN','طلب توثيق جديد','طلب التوثيق KYC-'||v_id||' يحتاج المراجعة.','fa-user-check','KYC-'||v_id);
  return jsonb_build_object('kyc_id',v_id,'reference','KYC-'||v_id,'status','PENDING');
end $$;

create or replace function public.mark_notifications_read(p_notification_ids bigint[])
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_user_id bigint := public.current_profile_id();
begin
  if public.is_admin() then
    update public.notifications set is_read=true where notification_id=any(p_notification_ids) and audience='ADMIN';
  else
    update public.notifications set is_read=true where notification_id=any(p_notification_ids) and user_id=v_user_id and audience='USER';
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- 4. Administrator-only workflows
-- ---------------------------------------------------------------------------

create or replace function public.admin_review_deposit(p_deposit_id bigint,p_decision text,p_note text default null)
returns void language plpgsql security definer set search_path=public as $$
declare v_admin bigint:=public.current_profile_id(); v_row public.deposit_requests%rowtype; v_new_balance numeric(20,8); v_decision text:=upper(p_decision);
begin
  if not public.is_admin() then raise exception 'not_authorized'; end if;
  if v_decision not in ('APPROVED','REJECTED') then raise exception 'invalid_decision'; end if;
  select * into v_row from public.deposit_requests where deposit_id=p_deposit_id for update;
  if not found then raise exception 'request_not_found'; end if;
  if upper(v_row.status)<>'PENDING' then raise exception 'request_already_reviewed'; end if;
  if v_decision='APPROVED' then
    update public.users set balance_usdt=coalesce(balance_usdt,0)+v_row.net_usdt,balance=coalesce(balance_usdt,0)+v_row.net_usdt where user_id=v_row.user_id returning balance_usdt into v_new_balance;
  end if;
  update public.deposit_requests set status=v_decision,admin_note=p_note,reviewed_by=v_admin,processed_at=now() where deposit_id=p_deposit_id;
  update public.transactions set status=case when v_decision='APPROVED' then 'COMPLETED' else 'REJECTED' end,balance_after=case when v_decision='APPROVED' then v_new_balance else balance_after end,updated_at=now() where request_id=p_deposit_id and type='DEPOSIT';
  insert into public.notifications(user_id,audience,title,message,icon,reference) values(v_row.user_id,'USER',case when v_decision='APPROVED' then 'تم قبول الإيداع' else 'تم رفض الإيداع' end,case when v_decision='APPROVED' then 'أضيف '||round(v_row.net_usdt,2)||' USDT إلى رصيدك.' else coalesce(p_note,'تعذر قبول الطلب. تواصل مع الدعم.') end,case when v_decision='APPROVED' then 'fa-circle-check' else 'fa-circle-xmark' end,v_row.reference);
  insert into public.audit_logs(actor_user_id,action,entity_type,entity_id,details) values(v_admin,'REVIEW_'||v_decision,'DEPOSIT',p_deposit_id::text,jsonb_build_object('note',p_note));
end $$;

create or replace function public.admin_review_withdraw(p_withdraw_id bigint,p_decision text,p_note text default null)
returns void language plpgsql security definer set search_path=public as $$
declare v_admin bigint:=public.current_profile_id(); v_row public.withdraw_requests%rowtype; v_new_balance numeric(20,8); v_decision text:=upper(p_decision);
begin
  if not public.is_admin() then raise exception 'not_authorized'; end if;
  if v_decision not in ('APPROVED','REJECTED') then raise exception 'invalid_decision'; end if;
  select * into v_row from public.withdraw_requests where withdraw_id=p_withdraw_id for update;
  if not found then raise exception 'request_not_found'; end if;
  if upper(v_row.status)<>'PENDING' then raise exception 'request_already_reviewed'; end if;
  if v_decision='REJECTED' then
    update public.users set balance_usdt=coalesce(balance_usdt,0)+v_row.amount_usdt,balance=coalesce(balance_usdt,0)+v_row.amount_usdt where user_id=v_row.user_id returning balance_usdt into v_new_balance;
  end if;
  update public.withdraw_requests set status=v_decision,admin_note=p_note,reviewed_by=v_admin,processed_at=now() where withdraw_id=p_withdraw_id;
  update public.transactions set status=case when v_decision='APPROVED' then 'COMPLETED' else 'REJECTED' end,balance_after=case when v_decision='REJECTED' then v_new_balance else balance_after end,updated_at=now() where request_id=p_withdraw_id and type in ('WITHDRAW','YER_PAYOUT');
  insert into public.notifications(user_id,audience,title,message,icon,reference) values(v_row.user_id,'USER',case when v_decision='APPROVED' then 'تم تنفيذ السحب' else 'تم رفض السحب' end,case when v_decision='APPROVED' then 'اكتمل طلب السحب '||v_row.reference||'.' else coalesce(p_note,'أعيد المبلغ المحجوز إلى رصيدك.') end,case when v_decision='APPROVED' then 'fa-circle-check' else 'fa-rotate-left' end,v_row.reference);
  insert into public.audit_logs(actor_user_id,action,entity_type,entity_id,details) values(v_admin,'REVIEW_'||v_decision,'WITHDRAW',p_withdraw_id::text,jsonb_build_object('note',p_note));
end $$;

create or replace function public.admin_review_kyc(p_kyc_id bigint,p_decision text,p_reason text default null)
returns void language plpgsql security definer set search_path=public as $$
declare v_admin bigint:=public.current_profile_id(); v_row public.kyc_requests%rowtype; v_decision text:=upper(p_decision);
begin
  if not public.is_admin() then raise exception 'not_authorized'; end if;
  if v_decision not in ('APPROVED','REJECTED') then raise exception 'invalid_decision'; end if;
  if v_decision='REJECTED' and nullif(trim(p_reason),'') is null then raise exception 'rejection_reason_required'; end if;
  select * into v_row from public.kyc_requests where kyc_id=p_kyc_id for update;
  if not found then raise exception 'request_not_found'; end if;
  if upper(v_row.status)<>'PENDING' then raise exception 'request_already_reviewed'; end if;
  update public.kyc_requests set status=v_decision,rejection_reason=case when v_decision='REJECTED' then p_reason else null end,reviewed_by=v_admin::text,reviewed_at=now(),updated_at=now() where kyc_id=p_kyc_id;
  update public.users set kyc_status=v_decision where user_id=v_row.user_id;
  insert into public.notifications(user_id,audience,title,message,icon,reference) values(v_row.user_id,'USER',case when v_decision='APPROVED' then 'تم توثيق حسابك' else 'يحتاج التوثيق إلى تعديل' end,case when v_decision='APPROVED' then 'اكتمل التحقق من هويتك ويمكنك الآن استخدام خدمات السحب.' else p_reason end,case when v_decision='APPROVED' then 'fa-user-check' else 'fa-id-card' end,'KYC-'||p_kyc_id);
  insert into public.audit_logs(actor_user_id,action,entity_type,entity_id,details) values(v_admin,'REVIEW_'||v_decision,'KYC',p_kyc_id::text,jsonb_build_object('reason',p_reason));
end $$;

create or replace function public.admin_set_user_status(p_user_id bigint,p_active boolean)
returns void language plpgsql security definer set search_path=public as $$
declare v_admin bigint:=public.current_profile_id();
begin
  if not public.is_admin() then raise exception 'not_authorized'; end if;
  if p_user_id=v_admin then raise exception 'cannot_disable_self'; end if;
  update public.users set is_active=case when p_active then 1 else 0 end,deleted_at=case when p_active then null else deleted_at end where user_id=p_user_id;
  if not found then raise exception 'user_not_found'; end if;
  insert into public.notifications(user_id,audience,title,message,icon) values(p_user_id,'USER',case when p_active then 'تم تفعيل حسابك' else 'تم تجميد حسابك' end,case when p_active then 'يمكنك استخدام حسابك مجددًا.' else 'تواصل مع خدمة العملاء لمعرفة التفاصيل.' end,'fa-user-lock');
  insert into public.audit_logs(actor_user_id,action,entity_type,entity_id) values(v_admin,case when p_active then 'ACTIVATE' else 'FREEZE' end,'USER',p_user_id::text);
end $$;

create or replace function public.admin_archive_user(p_user_id bigint,p_reason text)
returns void language plpgsql security definer set search_path=public as $$
declare v_admin bigint:=public.current_profile_id();
begin
  if not public.is_admin() then raise exception 'not_authorized'; end if;
  if p_user_id=v_admin then raise exception 'cannot_archive_self'; end if;
  if nullif(trim(p_reason),'') is null then raise exception 'archive_reason_required'; end if;
  update public.users set is_active=0,deleted_at=now(),deleted_reason=p_reason where user_id=p_user_id;
  if not found then raise exception 'user_not_found'; end if;
  insert into public.audit_logs(actor_user_id,action,entity_type,entity_id,details) values(v_admin,'ARCHIVE','USER',p_user_id::text,jsonb_build_object('reason',p_reason));
end $$;

create or replace function public.admin_search_transactions(p_query text default null,p_limit integer default 200)
returns table(transaction_id bigint,reference text,type text,status text,currency text,amount_usdt numeric,amount_yer numeric,description text,created_at timestamptz,user_id bigint,full_name text,email text)
language sql stable security definer set search_path=public as $$
  select t.transaction_id,t.reference,t.type::text,t.status::text,t.currency::text,t.amount_usdt,t.amount_yer,t.description,t.created_at,t.user_id,u.full_name::text,u.email::text
  from public.transactions t join public.users u on u.user_id=t.user_id
  where public.is_admin()
    and (nullif(trim(p_query),'') is null
      or t.reference ilike '%'||trim(p_query)||'%'
      or u.email ilike '%'||trim(p_query)||'%'
      or u.phone_number ilike '%'||trim(p_query)||'%'
      or u.full_name ilike '%'||trim(p_query)||'%')
  order by t.created_at desc
  limit least(greatest(coalesce(p_limit,200),1),500)
$$;

-- ---------------------------------------------------------------------------
-- 5. Row-level security: browser clients can never change balances directly
-- ---------------------------------------------------------------------------

alter table public.users enable row level security;
alter table public.kyc_requests enable row level security;
alter table public.exchange_rates enable row level security;
alter table public.payment_methods enable row level security;
alter table public.deposit_requests enable row level security;
alter table public.withdraw_requests enable row level security;
alter table public.transactions enable row level security;
alter table public.notifications enable row level security;
alter table public.audit_logs enable row level security;

-- Remove previous policies on the PayFlow tables so permissive legacy policies cannot remain.
do $$
declare p record;
begin
  for p in select schemaname,tablename,policyname from pg_policies
    where schemaname='public' and tablename in ('users','kyc_requests','exchange_rates','payment_methods','deposit_requests','withdraw_requests','transactions','notifications','audit_logs')
  loop execute format('drop policy if exists %I on %I.%I',p.policyname,p.schemaname,p.tablename); end loop;
end $$;

create policy users_select_own_or_admin on public.users for select to authenticated using (auth_user_id=auth.uid() or public.is_admin());
create policy kyc_select_own_or_admin on public.kyc_requests for select to authenticated using (user_id=public.current_profile_id() or public.is_admin());
create policy rates_read_authenticated on public.exchange_rates for select to authenticated using (true);
create policy rates_admin_update on public.exchange_rates for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy methods_read_active_or_admin on public.payment_methods for select to authenticated using (is_active=true or public.is_admin());
create policy methods_admin_insert on public.payment_methods for insert to authenticated with check (public.is_admin());
create policy methods_admin_update on public.payment_methods for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy methods_admin_delete on public.payment_methods for delete to authenticated using (public.is_admin());
create policy deposits_select_own_or_admin on public.deposit_requests for select to authenticated using (user_id=public.current_profile_id() or public.is_admin());
create policy withdrawals_select_own_or_admin on public.withdraw_requests for select to authenticated using (user_id=public.current_profile_id() or public.is_admin());
create policy transactions_select_own_or_admin on public.transactions for select to authenticated using (user_id=public.current_profile_id() or public.is_admin());
create policy notifications_select_own_or_admin on public.notifications for select to authenticated using ((audience='USER' and user_id=public.current_profile_id()) or (audience='ADMIN' and public.is_admin()));
create policy audit_admin_select on public.audit_logs for select to authenticated using (public.is_admin());

revoke all on public.users,public.kyc_requests,public.deposit_requests,public.withdraw_requests,public.transactions,public.notifications,public.audit_logs from anon;
revoke insert,update,delete on public.users,public.kyc_requests,public.deposit_requests,public.withdraw_requests,public.transactions,public.notifications,public.audit_logs from authenticated;
grant select on public.users,public.kyc_requests,public.deposit_requests,public.withdraw_requests,public.transactions,public.notifications to authenticated;
grant select on public.exchange_rates,public.payment_methods to authenticated;
grant update on public.exchange_rates to authenticated;
grant insert,update,delete on public.payment_methods to authenticated;
grant usage,select on all sequences in schema public to authenticated;

revoke all on function public.create_deposit_request(numeric,bigint,text,text,text) from public,anon;
revoke all on function public.create_withdraw_request(numeric,text,text,text,bigint,text) from public,anon;
revoke all on function public.lookup_transfer_recipient(text) from public,anon;
revoke all on function public.internal_transfer(text,numeric,text) from public,anon;
revoke all on function public.submit_kyc_request(text,text,text,text,text) from public,anon;
revoke all on function public.mark_notifications_read(bigint[]) from public,anon;
revoke all on function public.admin_review_deposit(bigint,text,text) from public,anon;
revoke all on function public.admin_review_withdraw(bigint,text,text) from public,anon;
revoke all on function public.admin_review_kyc(bigint,text,text) from public,anon;
revoke all on function public.admin_set_user_status(bigint,boolean) from public,anon;
revoke all on function public.admin_archive_user(bigint,text) from public,anon;
revoke all on function public.admin_search_transactions(text,integer) from public,anon;

grant execute on function public.create_deposit_request(numeric,bigint,text,text,text) to authenticated;
grant execute on function public.create_withdraw_request(numeric,text,text,text,bigint,text) to authenticated;
grant execute on function public.lookup_transfer_recipient(text) to authenticated;
grant execute on function public.internal_transfer(text,numeric,text) to authenticated;
grant execute on function public.submit_kyc_request(text,text,text,text,text) to authenticated;
grant execute on function public.mark_notifications_read(bigint[]) to authenticated;
grant execute on function public.admin_review_deposit(bigint,text,text) to authenticated;
grant execute on function public.admin_review_withdraw(bigint,text,text) to authenticated;
grant execute on function public.admin_review_kyc(bigint,text,text) to authenticated;
grant execute on function public.admin_set_user_status(bigint,boolean) to authenticated;
grant execute on function public.admin_archive_user(bigint,text) to authenticated;
grant execute on function public.admin_search_transactions(text,integer) to authenticated;

-- ---------------------------------------------------------------------------
-- 6. Private storage for receipts and identity documents
-- ---------------------------------------------------------------------------

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values
  ('deposit-proofs','deposit-proofs',false,7340032,array['image/jpeg','image/png','image/webp','application/pdf']),
  ('kyc-documents','kyc-documents',false,7340032,array['image/jpeg','image/png','image/webp'])
on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists payflow_upload_deposit_proof on storage.objects;
drop policy if exists payflow_read_deposit_proof on storage.objects;
drop policy if exists payflow_delete_deposit_proof on storage.objects;
drop policy if exists payflow_upload_kyc_document on storage.objects;
drop policy if exists payflow_read_kyc_document on storage.objects;
drop policy if exists payflow_delete_kyc_document on storage.objects;

create policy payflow_upload_deposit_proof on storage.objects for insert to authenticated
with check(bucket_id='deposit-proofs' and (storage.foldername(name))[1]=auth.uid()::text);
create policy payflow_read_deposit_proof on storage.objects for select to authenticated
using(bucket_id='deposit-proofs' and ((storage.foldername(name))[1]=auth.uid()::text or public.is_admin()));
create policy payflow_delete_deposit_proof on storage.objects for delete to authenticated
using(bucket_id='deposit-proofs' and (storage.foldername(name))[1]=auth.uid()::text);
create policy payflow_upload_kyc_document on storage.objects for insert to authenticated
with check(bucket_id='kyc-documents' and (storage.foldername(name))[1]=auth.uid()::text);
create policy payflow_read_kyc_document on storage.objects for select to authenticated
using(bucket_id='kyc-documents' and ((storage.foldername(name))[1]=auth.uid()::text or public.is_admin()));
create policy payflow_delete_kyc_document on storage.objects for delete to authenticated
using(bucket_id='kyc-documents' and (storage.foldername(name))[1]=auth.uid()::text);

-- Starter payment methods. Edit them later from the Admin page.
insert into public.payment_methods(name,category,account_name,account_number,instructions,sort_order)
values
  ('محفظة كريمي','BOTH','PayFlow','أضف رقم حسابك','اكتب الرقم المرجعي في ملاحظة التحويل.',1),
  ('محفظة جوالي','BOTH','PayFlow','أضف رقم المحفظة','احتفظ بصورة الإيصال ثم ارفعها في الطلب.',2),
  ('تحويل بنكي محلي','BOTH','PayFlow','PayFlow Exchange','أضف رقم الحساب','يجب أن يطابق اسم المرسل البيانات المدخلة.',3)
on conflict do nothing;

commit;

-- IMPORTANT AFTER RUNNING:
-- 1) Sign up once through register.html using the email that will be the manager.
-- 2) Then run this separately after replacing the email:
--    update public.users set role='ADMIN' where lower(email)=lower('admin@example.com');
--
-- Optional security cleanup after confirming all old accounts can sign in with Supabase Auth:
--    update public.users set password_hash=null where password_hash is not null;
